load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "configutil",
    srcs = ["secrets.go"],
    importpath = "github.com/rmrobinson/house/service/lib/configutil",
    visibility = ["//visibility:public"],
    deps = ["@in_gopkg_yaml_v3//:yaml_v3"],
)

go_test(
    name = "configutil_test",
    srcs = ["secrets_test.go"],
    embed = [":configutil"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@in_gopkg_yaml_v3//:yaml_v3",
    ],
)
