load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "policy",
    srcs = [
        "attribute_conditions.go",
        "bindings.go",
        "bus.go",
        "cache.go",
        "condition.go",
        "defaults.go",
        "engine.go",
        "grpc.go",
        "location_conditions.go",
        "notify.go",
        "notify_bindings.go",
        "policy.go",
        "store.go",
        "sun.go",
    ],
    embedsrcs = [
        "scripts/sys_occupancy.lua",
        "scripts/sys_power_restore.lua",
        "migrations/000001_setup.down.sql",
        "migrations/000001_setup.up.sql",
    ],
    importpath = "github.com/rmrobinson/house/service/policy",
    visibility = ["//visibility:public"],
    deps = [
        "//api",
        "@com_github_golang_migrate_migrate_v4//:migrate",
        "@com_github_golang_migrate_migrate_v4//database/sqlite",
        "@com_github_golang_migrate_migrate_v4//source/iofs",
        "@com_github_yuin_gopher_lua//:gopher-lua",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//types/known/emptypb",
        "@org_golang_google_protobuf//types/known/timestamppb",
        "@org_uber_go_zap//:zap",
    ],
)

go_test(
    name = "policy_test",
    srcs = [
        "attribute_conditions_test.go",
        "bindings_test.go",
        "bus_test.go",
        "condition_test.go",
        "defaults_test.go",
        "engine_test.go",
        "fakehome_test.go",
        "grpc_test.go",
        "location_conditions_test.go",
        "notify_bindings_test.go",
        "policy_test.go",
        "store_test.go",
        "sun_test.go",
    ],
    embed = [":policy"],
    deps = [
        "//api",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@com_github_yuin_gopher_lua//:gopher-lua",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_uber_go_zap//:zap",
        "@org_uber_go_zap//zaptest",
        "@org_uber_go_zap//zaptest/observer",
    ],
)
