load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "frigate",
    srcs = ["client.go"],
    importpath = "github.com/rmrobinson/house/bridges/frigate/frigate",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_gorilla_websocket//:websocket",
        "@org_uber_go_zap//:zap",
    ],
)
