load("@rules_go//go:def.bzl", "go_library", "go_test")
load("@rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "castctrl_proto",
    srcs = ["cast_channel.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "castctrl_go_proto",
    importpath = "github.com/rmrobinson/house/bridges/lib/castctrl",
    proto = ":castctrl_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "castctrl",
    srcs = [
        "conn.go",
        "namespaces.go",
        "payloads.go",
        "session.go",
    ],
    embed = [":castctrl_go_proto"],
    importpath = "github.com/rmrobinson/house/bridges/lib/castctrl",
    visibility = ["//visibility:public"],
    deps = [
        "//backoffutil",
        "@org_golang_google_protobuf//proto",
        "@org_uber_go_zap//:zap",
    ],
)

go_test(
    name = "castctrl_test",
    srcs = [
        "conn_test.go",
        "session_test.go",
    ],
    embed = [":castctrl"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@org_golang_google_protobuf//proto",
        "@org_uber_go_zap//zaptest",
    ],
)
