load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "facade",
    srcs = [
        "facade.go",
        "upstream.go",
    ],
    importpath = "github.com/rmrobinson/house/service/bridge/facade",
    visibility = ["//visibility:public"],
    deps = [
        "//api",
        "//api/command",
        "//api/device",
        "//grpcutil",
        "//service/bridge",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//proto",
        "@org_uber_go_zap//:zap",
    ],
)

go_test(
    name = "facade_test",
    srcs = [
        "facade_test.go",
        "stream_test.go",
        "upstream_test.go",
    ],
    embed = [":facade"],
    deps = [
        "//api",
        "//api/device",
        "//service/bridge",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_protobuf//proto",
        "@org_uber_go_zap//zaptest",
    ],
)
