load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "protoreflectutil",
    srcs = ["protoreflectutil.go"],
    importpath = "github.com/rmrobinson/house/service/lib/protoreflectutil",
    visibility = ["//visibility:public"],
    deps = [
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoreflect",
    ],
)

go_test(
    name = "protoreflectutil_test",
    srcs = ["protoreflectutil_test.go"],
    embed = [":protoreflectutil"],
    deps = [
        "//api/device",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
