load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "frigate_lib",
    srcs = [
        "bridge.go",
        "camera.go",
        "main.go",
    ],
    importpath = "github.com/rmrobinson/house/bridges/frigate",
    visibility = ["//visibility:private"],
    deps = [
        "//api",
        "//api/command",
        "//api/device",
        "//api/trait",
        "//bridges/frigate/frigate",
        "//service/bridge",
        "//service/lib/configutil",
        "@com_github_google_uuid//:uuid",
        "@com_github_spf13_viper//:viper",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//types/known/timestamppb",
        "@org_uber_go_zap//:zap",
    ],
)

go_binary(
    name = "frigate",
    embed = [":frigate_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "frigate_test",
    srcs = [
        "camera_test.go",
        "motion_test.go",
    ],
    embed = [":frigate_lib"],
    deps = [
        "//api/trait",
        "//bridges/frigate/frigate",
        "@com_github_gorilla_websocket//:websocket",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@org_uber_go_zap//:zap",
    ],
)
