load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "example_lib",
    srcs = [
        "bridge.go",
        "main.go",
    ],
    importpath = "github.com/rmrobinson/house/bridges/example",
    visibility = ["//visibility:private"],
    deps = [
        "//api",
        "//api/command",
        "//api/device",
        "//api/trait",
        "//service/bridge",
        "@org_uber_go_zap//:zap",
    ],
)

go_binary(
    name = "example",
    embed = [":example_lib"],
    visibility = ["//visibility:public"],
)
