load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "bridgefacaded_lib",
    srcs = ["main.go"],
    importpath = "github.com/rmrobinson/house/service/bridge/facade/cmd/bridgefacaded",
    visibility = ["//visibility:private"],
    deps = [
        "//api",
        "//service/bridge/facade",
        "@com_github_google_uuid//:uuid",
        "@com_github_spf13_viper//:viper",
        "@org_golang_google_grpc//:grpc",
        "@org_uber_go_zap//:zap",
    ],
)

go_binary(
    name = "bridgefacaded",
    embed = [":bridgefacaded_lib"],
    visibility = ["//visibility:public"],
)
